const blogPosts = [
  {
    slug: 'build-astrology-app',
    title: 'How to Build an Astrology App with AstroVakta API',
    date: 'July 28, 2026',
    author: 'Rohan Sharma',
    readTime: '8 min read',
    tag: 'Tutorial',
    tagColor: '#7c3aed',
    excerpt: 'A step-by-step guide to building a fully functional Vedic astrology app using the AstroVakta API. From birth charts to AI-powered horoscopes — we cover everything.',
    body: [
      { type: 'h2', text: 'Why Build an Astrology App?' },
      { type: 'p', text: 'The global astrology market is projected to reach $22 billion by 2030. With smartphones in every pocket, astrology apps have become the primary way people engage with their horoscopes, birth charts, and compatibility analysis. But building a reliable astrology app is hard — you need accurate planetary calculations, divisional charts, nakshatra data, dasha systems, and more.' },
      { type: 'p', text: 'This is where AstroVakta comes in. Instead of implementing the Swiss Ephemeris yourself or maintaining complex astronomical calculations, you can use our REST API to get everything you need in a single JSON response.' },
      { type: 'h2', text: 'Step 1: Get Your API Key' },
      { type: 'p', text: 'Sign up for a free account at astrovakta.com. You get 500 free API calls per month — more than enough to prototype and test your app. Once you have your API key (looks like avk_live_xxx), you\'re ready to make your first API call.' },
      { type: 'h2', text: 'Step 2: Generate a Birth Chart' },
      { type: 'p', text: 'The birth chart endpoint is your starting point. Send the user\'s date of birth, time of birth, latitude, longitude, and timezone — and get back a complete D1 Rasi chart with all 9 planets, house placements, nakshatras, zodiac signs, degrees, retrograde status, combustion status, and dignities.' },
      { type: 'pre', text: `POST /chart/birth-chart
{
  "dateOfBirth": "1990-05-15",
  "timeOfBirth": "14:30",
  "latitude": 28.6139,
  "longitude": 77.2090,
  "timezone": "Asia/Kolkata"
}` },
      { type: 'h2', text: 'Step 3: Add Daily Horoscopes' },
      { type: 'p', text: 'Use the daily horoscope endpoint to generate personalized daily readings based on real-time transits over the natal chart. The endpoint returns a natural language horoscope that you can display directly in your app with minimal processing.' },
      { type: 'h2', text: 'Step 4: Integrate Compatibility Matching' },
      { type: 'p', text: 'The compatibility (kundali milan) endpoint takes two birth profiles and returns Ashtakoot guna milan scores, individual koota scores, dosha analysis, and a compatibility verdict. This is essential for matrimony platforms and relationship apps.' },
      { type: 'h2', text: 'Step 5: Add AI-Powered Insights' },
      { type: 'p', text: 'AstroVakta supports BYO AI keys for OpenAI, Claude, Groq, and Together. Configure your AI provider in the dashboard, then use the AI chat endpoint to get natural language interpretations of any chart data. The AI agent receives full chart context — planet-by-planet, house-by-house, nakshatra-by-nakshatra.' },
      { type: 'h2', text: 'Step 6: Generate PDF Reports' },
      { type: 'p', text: 'For premium features, use the PDF report generation endpoint. It produces a 22-section branded report with cover page, birth chart visualization, planet table, divisional charts, predictions, dosha analysis, remedies, and more. Perfect for selling downloadable reports.' },
      { type: 'h2', text: 'Wrapping Up' },
      { type: 'p', text: 'Building an astrology app has never been easier. With AstroVakta handling all the heavy lifting — precise calculations, chart generation, AI, PDFs — you can focus on building a beautiful UI and growing your user base. Get started today with 500 free API calls.' },
    ],
  },
  {
    slug: 'vedic-charts-developer-guide',
    title: 'Understanding Vedic Astrology Charts: A Developer\'s Guide',
    date: 'July 22, 2026',
    author: 'Dr. Ananya Gupta',
    readTime: '10 min read',
    tag: 'Guide',
    tagColor: '#3b82f6',
    excerpt: 'A technical deep-dive into the chart types supported by AstroVakta — from D1 Rasi to D60 Shashtiamsha. Understand what each divisional chart represents and how to use them in your application.',
    body: [
      { type: 'h2', text: 'Why Divisional Charts Matter' },
      { type: 'p', text: 'In Vedic astrology, the birth chart (D1 or Rasi) shows the broad canvas of a person\'s life. But to dive deep into specific areas — career, marriage, children, wealth, education — astrologers use divisional charts (Vargas). Each divisional chart divides the zodiac signs into a specific number of parts, revealing finer details.' },
      { type: 'p', text: 'AstroVakta supports the full D1 through D60 divisional chart suite, plus specialized charts like Navamsa (D9), Sudarshana Chakra, Bhava Chalit, and Moon Chart. Let\'s explore what each offers.' },
      { type: 'h2', text: 'D1 — Rasi (Birth Chart)' },
      { type: 'p', text: 'The primary birth chart. Shows planetary positions in 12 houses with nakshatra, zodiac sign, degree, retrograde status, combustion status, and dignity for each of the 9 Vedic planets. This is your starting point for any astrology app.' },
      { type: 'h2', text: 'D9 — Navamsa' },
      { type: 'p', text: 'The most important divisional chart. Used for marriage compatibility, spouse characteristics, and deeper planetary strength analysis. Each 30-degree sign is divided into 9 parts of 3°20\'. A planet\'s position in D9 can dramatically change its interpretation from D1.' },
      { type: 'h2', text: 'D2 — Hora' },
      { type: 'p', text: 'Divides each sign into 2 parts. Relates to wealth, finances, and family. Essential for financial astrology features in your app.' },
      { type: 'h2', text: 'D3 — Drekkana' },
      { type: 'p', text: 'Divides each sign into 3 parts. Relates to siblings, courage, and co-born. Useful for family-oriented applications.' },
      { type: 'h2', text: 'D10 — Dashamamsa' },
      { type: 'p', text: 'The career chart. Divides each sign into 10 parts. Shows professional life, reputation, and achievements. Crucial for career prediction features.' },
      { type: 'h2', text: 'Specialized Charts' },
      { type: 'p', text: 'Beyond divisional charts, AstroVakta provides: the Sudarshana Chakra (a holistic 3-ring view combining D1, D9, and D12), Bhava Chalit (houses shifted to account for cusp-based analysis), and Moon Chart (chart with Moon as ascendant for emotional perspective).' },
      { type: 'h2', text: 'Chart Styles' },
      { type: 'p', text: 'You can request charts in three visual styles: North Indian (diamond grid), South Indian (square grid with fixed signs), and East Indian (rectangular). SVG output is supported for all chart styles and divisional charts, making it easy to embed beautiful charts directly in your application.' },
      { type: 'h2', text: 'Best Practices for Developers' },
      { type: 'p', text: 'Start with D1 for the main birth chart UI. Add D9 for relationship/marriage features. Include D10 for career predictions. Remember that divisional charts amplify or modify D1 indications — they don\'t replace them. Always cross-reference D1 with relevant divisional charts for comprehensive analysis.' },
    ],
  },
  {
    slug: 'top-astrology-api-features-2026',
    title: 'Top 10 Astrology API Features Your App Needs in 2026',
    date: 'July 18, 2026',
    author: 'Vikram Patel',
    readTime: '6 min read',
    tag: 'Features',
    tagColor: '#ec4899',
    excerpt: 'The astrology tech landscape is evolving fast. Here are the 10 must-have features for any modern astrology app in 2026 — and how AstroVakta helps you ship them.',
    body: [
      { type: 'h2', text: '1. Real-Time Birth Chart Generation' },
      { type: 'p', text: 'Users expect instant results. AstroVakta\'s birth chart endpoint returns complete D1 Rasi charts with all 9 planets, nakshatras, house placements, dignities, and combustion status in under 500ms. No caching tricks — actual Swiss Ephemeris calculations at speed.' },
      { type: 'h2', text: '2. Daily Horoscopes Based on Real Transits' },
      { type: 'p', text: 'Generic sun-sign horoscopes are a thing of the past. Generate personalized daily, weekly, monthly, and yearly horoscopes based on actual planetary transits over the user\'s natal chart. Every reading is unique to the user.' },
      { type: 'h2', text: '3. AI-Powered Interpretations' },
      { type: 'p', text: 'Raw chart data means nothing to most users. With the BYO AI key feature, you can pass full chart context to LLMs for natural-language interpretations. The AI receives planet-by-planet, house-by-house, nakshatra-by-nakshatra data for truly informed responses.' },
      { type: 'h2', text: '4. Full Dasha System Support' },
      { type: 'p', text: 'Vimshottari Dasha with 4 levels (Maha, Antar, Pratyantar, Sookshma), Chara Dasha, and Yogini Dasha — all calculated on-the-fly with exact planetary periods. Essential for timing predictions.' },
      { type: 'h2', text: '5. Comprehensive Dosha Detection' },
      { type: 'p', text: 'Mangal Dosha, Kaal Sarp Dosha, Sade Sati, Pitra Dosha, Shani Dosha and more — each with severity ratings, sub-types, and personalized remedies. This is what keeps users coming back for paid reports.' },
      { type: 'h2', text: '6. Beautiful Chart Visualizations' },
      { type: 'p', text: 'SVG chart generation for all chart styles (North Indian, South Indian, East Indian) and divisional charts (D1-D60). Embeddable as web components or downloadable as PNG/SVG. Your charts will look stunning.' },
      { type: 'h2', text: '7. Branded PDF Reports' },
      { type: 'p', text: 'The PDF engine generates 22-section reports with cover pages, charts, and detailed analysis. White-label it with your branding. Sell downloadable reports directly from your app.' },
      { type: 'h2', text: '8. Panchang & Muhurat' },
      { type: 'p', text: 'Full Panchang (Tithi, Nakshatra, Yoga, Karana, Vara) plus auspicious muhurat calculations for events like weddings, business openings, and travel. Essential for Indian-market apps.' },
      { type: 'h2', text: '9. Multi-Provider AI Flexibility' },
      { type: 'p', text: 'Not locked into one AI provider. Configure OpenAI, Anthropic Claude, Groq, and Together AI simultaneously. Switch providers per request. Test connectivity from the dashboard. Your users get the best AI experience.' },
      { type: 'h2', text: '10. Enterprise-Grade Infrastructure' },
      { type: 'p', text: 'AES-256 encrypted API keys, Redis-backed background job queues, rate limiting by tier, usage analytics dashboard, and 99.9% uptime SLA. Built for production from day one.' },
    ],
  },
  {
    slug: 'ai-vedic-astrology-overview',
    title: 'Integrating AI with Vedic Astrology: A Technical Overview',
    date: 'July 12, 2026',
    author: 'Rohan Sharma',
    readTime: '7 min read',
    tag: 'AI',
    tagColor: '#8b5cf6',
    excerpt: 'How AstroVakta combines LLMs with precise astrological data to generate intelligent chart interpretations. A look under the hood at the multi-provider AI pipeline.',
    body: [
      { type: 'h2', text: 'The Challenge: AI + Astrology' },
      { type: 'p', text: 'LLMs are incredibly powerful but they lack precise astrological calculation capability. When you ask an LLM about your birth chart, it guesses — often incorrectly — about planetary positions, house placements, and nakshatras. Our solution: compute everything with Swiss Ephemeris precision first, then feed structured context to the AI.' },
      { type: 'h2', text: 'How AstroVakta\'s AI Pipeline Works' },
      { type: 'p', text: 'When you call the AI chat or AI interpretation endpoint, AstroVakta first computes the complete chart — all 9 planets, 12 houses, nakshatras, zodiac signs, degrees, retrograde status, combustion status, dignities, divisional charts, dashas, transits, and yogas. This computed data is then structured into a comprehensive context prompt that is sent to your chosen AI provider.' },
      { type: 'p', text: 'The key insight: the AI is never asked to calculate anything. It receives a pre-computed, structured dataset and is instructed to interpret it in natural language. This eliminates hallucination and ensures factual accuracy.' },
      { type: 'h2', text: 'Context Structure' },
      { type: 'pre', text: `{
  "ascendant": { "sign": "Taurus", "nakshatra": "Krittika", "lord": "Venus" },
  "planets": [
    { "name": "Sun", "sign": "Aries", "house": 12, 
      "nakshatra": "Ashwini", "dignity": "Exalted", 
      "retrograde": false, "combust": false }
  ],
  "yogas": ["Gajakesari", "Budhaditya"],
  "current_transits": { "Saturn": "transiting 8H Aquarius" },
  "current_dasha": { "Maha": "Venus", "Antar": "Sun" }
}` },
      { type: 'h2', text: 'Multi-Provider Architecture' },
      { type: 'p', text: 'We support four AI providers out of the box: OpenAI (GPT-4o), Anthropic (Claude 3.5 Sonnet), Groq (Llama fast inference), and Together AI (open-source models). Your keys are AES-256 encrypted. You can configure all four simultaneously and choose which to use per request.' },
      { type: 'h2', text: 'Building an AI Astrologer' },
      { type: 'p', text: 'To build an AI astrologer feature: (1) Configure your AI provider in the dashboard, (2) Send the user\'s question and birth details to the AI chat endpoint, (3) Receive a context-aware response. The AI "knows" the user\'s exact chart and responds accordingly — no generic horoscope fluff.' },
      { type: 'h2', text: 'Real-World Applications' },
      { type: 'p', text: 'Developers are using this pipeline for: AI-powered daily horoscopes, automated relationship compatibility reports, career guidance consultations, personalized gemstone recommendations, real-time transit impact analysis, and interactive chat-based astrology consultations.' },
      { type: 'h2', text: 'Getting Started' },
      { type: 'p', text: 'Sign up for a free account, get your API key, and add your AI provider keys in the dashboard. Then call /ai/v2/chat with any question and birth details. Try it in our API sandbox first — no code required. The AI pipeline is available on all tiers, including Free.' },
    ],
  },
]

export default blogPosts
