import { useState, useRef, useCallback } from 'react'
import { motion } from 'framer-motion'
import { Play, Download, Settings, ChevronDown, ChevronUp, Loader2, FileText, Palette, Image, MapPin, X } from 'lucide-react'
import toast from 'react-hot-toast'
import api from '../lib/api.js'
import ReportTemplate from './kundali/ReportTemplate.jsx'
import './kundali/report.css'

const DEFAULT_BRANDING = {
  brandName: 'AstroVakta',
  logoUrl: '',
  headerText: 'Vedic Birth Chart Report',
  footerText: 'Generated by AstroVakta · Vedic Astrology API',
  primaryColor: '#7c3aed',
  secondaryColor: '#6366f1',
  coverTitle: 'Vedic Birth Chart Report',
  coverSubtitle: 'Comprehensive Kundali Analysis',
  backPageMessage: 'This report is generated based on Vedic astrological principles using the sidereal zodiac with Lahiri ayanamsa. The predictions and analysis are based on traditional Jyotish scriptures and should be used for guidance purposes. For personalized consultation, please contact a qualified Vedic astrologer.',
  clientName: '',
}

const DEFAULT_BIRTH = {
  dateOfBirth: '1990-05-15',
  timeOfBirth: '10:30',
  latitude: 28.6139,
  longitude: 77.209,
  timezone: 'Asia/Kolkata',
  locationName: 'New Delhi, India',
}

const API_KEY = import.meta.env.VITE_API_KEY || localStorage.getItem('user_api_key') || ''

function LocationSearch({ value, onSelect }) {
  const [query, setQuery] = useState('')
  const [results, setResults] = useState([])
  const [open, setOpen] = useState(false)
  const [loading, setLoading] = useState(false)
  const debounceRef = useRef(null)
  const wrapperRef = useRef(null)

  const search = (q) => {
    if (debounceRef.current) clearTimeout(debounceRef.current)
    if (!q || q.length < 2) { setResults([]); return }
    debounceRef.current = setTimeout(async () => {
      setLoading(true)
      try {
        const res = await api.get('/api/location/search', { params: { q, limit: 5 }, headers: { 'X-API-Key': API_KEY } })
        setResults(res.data?.locations || [])
        setOpen(true)
      } catch { setResults([]) }
      setLoading(false)
    }, 300)
  }

  const handleSelect = async (loc) => {
    setQuery('')
    setResults([])
    setOpen(false)
    let tz = 'Asia/Kolkata'
    try {
      const tzRes = await api.get('/api/location/timezone', { params: { lat: loc.latitude, lon: loc.longitude }, headers: { 'X-API-Key': API_KEY } })
      tz = tzRes.data?.timezone || tz
    } catch {}
    onSelect({ latitude: loc.latitude, longitude: loc.longitude, timezone: tz, locationName: loc.displayName })
  }

  return (
    <div ref={wrapperRef} style={{ position: 'relative' }}>
      <label style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 12, color: '#94a3b8', marginBottom: 4 }}>
        <MapPin size={12} /> Birth Location
      </label>
      {value && (
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '8px 12px', background: 'rgba(124,58,237,0.1)', borderRadius: 8, marginBottom: 6 }}>
          <MapPin size={14} color="#a78bfa" />
          <span style={{ flex: 1, fontSize: 13, color: '#e2e8f0' }}>{value}</span>
          <button onClick={() => onSelect({ latitude: null, longitude: null, timezone: '', locationName: '' })}
            style={{ background: 'none', border: 'none', color: '#64748b', cursor: 'pointer', padding: 2 }}>
            <X size={14} />
          </button>
        </div>
      )}
      <div style={{ position: 'relative' }}>
        <input className="input-field" placeholder="Search city or place..." value={query}
          onChange={(e) => { setQuery(e.target.value); search(e.target.value) }}
          onFocus={() => { if (results.length) setOpen(true) }} style={{ fontSize: 13, paddingRight: 32 }} />
        {loading && <Loader2 size={14} color="#64748b" style={{ position: 'absolute', right: 10, top: '50%', transform: 'translateY(-50%)', animation: 'spin 1s linear infinite' }} />}
      </div>
      {open && results.length > 0 && (
        <div style={{ position: 'absolute', top: '100%', left: 0, right: 0, zIndex: 50, background: '#12122a', border: '1px solid rgba(124,58,237,0.25)', borderRadius: 10, marginTop: 4, overflow: 'hidden', boxShadow: '0 12px 40px rgba(0,0,0,0.5)' }}>
          {results.map((loc, i) => (
            <button key={i} onClick={() => handleSelect(loc)}
              style={{ display: 'flex', alignItems: 'flex-start', gap: 10, width: '100%', padding: '10px 14px', background: 'transparent', border: 'none', color: '#e2e8f0', cursor: 'pointer', textAlign: 'left', borderBottom: i < results.length - 1 ? '1px solid rgba(100,116,139,0.15)' : 'none' }}>
              <MapPin size={14} color="#a78bfa" style={{ marginTop: 2, flexShrink: 0 }} />
              <div>
                <div style={{ fontSize: 13, fontWeight: 500 }}>{loc.displayName}</div>
                <div style={{ fontSize: 11, color: '#64748b', marginTop: 2 }}>{loc.latitude?.toFixed(4)}, {loc.longitude?.toFixed(4)}</div>
              </div>
            </button>
          ))}
        </div>
      )}
    </div>
  )
}

function buildBirthData(birth) {
  return {
    dateOfBirth: birth.dateOfBirth,
    timeOfBirth: birth.timeOfBirth,
    latitude: birth.latitude,
    longitude: birth.longitude,
    timezone: birth.timezone,
  }
}

const ALL_APIS = [
  { key: 'kundli', path: '/api/kundli' },
  { key: 'panchang', path: '/horoscope/panchang' },
  { key: 'rahuKaal', path: '/horoscope/panchang/rahu-kaal' },
  { key: 'gulikaKaal', path: '/horoscope/panchang/gulika-kaal' },
  { key: 'yamaganda', path: '/horoscope/panchang/yamaganda' },
  { key: 'choghadiya', path: '/horoscope/panchang/choghadiya' },
  { key: 'dasha', path: '/horoscope/dasha/vimshottari' },
  { key: 'currentDasha', path: '/horoscope/dasha/current' },
  { key: 'charaDasha', path: '/horoscope/dasha/chara' },
  { key: 'yoginiDasha', path: '/dasha/yogini' },
  { key: 'bhavaChalit', path: '/horoscope/bhava-chalit' },
  { key: 'yogas', path: '/horoscope/yoga/predictions' },
  { key: 'doshas', path: '/horoscope/dosha/compute' },
  { key: 'transit', path: '/horoscope/transit' },
  { key: 'career', path: '/horoscope/career' },
  { key: 'finance', path: '/horoscope/finance' },
  { key: 'health', path: '/horoscope/health' },
  { key: 'love', path: '/horoscope/love' },
  { key: 'education', path: '/horoscope/education' },
  { key: 'child', path: '/horoscope/child' },
  { key: 'foreign', path: '/horoscope/foreign' },
  { key: 'luckyColor', path: '/lucky/color' },
  { key: 'luckyNumber', path: '/lucky/number' },
  { key: 'luckyDay', path: '/lucky/day' },
  { key: 'luckyMetal', path: '/lucky/metal' },
  { key: 'gemstone', path: '/api/gemstone/recommendation' },
  { key: 'rudraksha', path: '/api/rudraksha/recommendation' },
  { key: 'varshaphal', path: '/horoscope/varshaphal', extraBody: { year: new Date().getFullYear() } },
]

const CHART_APIS = [
  { key: 'rasiSvg', path: '/chart/svg' },
  { key: 'navamsaSvg', path: '/chart/navamsa-svg' },
  { key: 'moonSvg', path: '/chart/moon-svg' },
  { key: 'horaSvg', path: '/chart/hora-svg' },
  { key: 'eastSvg', path: '/chart/east-svg' },
  { key: 'sudarshanaSvg', path: '/chart/sudarshana-svg' },
]

const DIVISIONAL_APIS = [
  { key: 'd3Svg', name: 'D3', path: '/chart/divisional-svg' },
  { key: 'd7Svg', name: 'D7', path: '/chart/divisional-svg' },
  { key: 'd10Svg', name: 'D10', path: '/chart/divisional-svg' },
  { key: 'd12Svg', name: 'D12', path: '/chart/divisional-svg' },
  { key: 'd16Svg', name: 'D16', path: '/chart/divisional-svg' },
  { key: 'd20Svg', name: 'D20', path: '/chart/divisional-svg' },
  { key: 'd24Svg', name: 'D24', path: '/chart/divisional-svg' },
  { key: 'd27Svg', name: 'D27', path: '/chart/divisional-svg' },
  { key: 'd30Svg', name: 'D30', path: '/chart/divisional-svg' },
  { key: 'd40Svg', name: 'D40', path: '/chart/divisional-svg' },
  { key: 'd45Svg', name: 'D45', path: '/chart/divisional-svg' },
  { key: 'd60Svg', name: 'D60', path: '/chart/divisional-svg' },
]

export default function KundaliReport() {
  const [birth, setBirth] = useState(DEFAULT_BIRTH)
  const [branding, setBranding] = useState(DEFAULT_BRANDING)
  const [showBranding, setShowBranding] = useState(false)
  const [loading, setLoading] = useState(false)
  const [progress, setProgress] = useState({ done: 0, total: 0, current: '' })
  const [reportData, setReportData] = useState(null)
  const [generatingPdf, setGeneratingPdf] = useState(false)
  const reportRef = useRef(null)

  const totalApis = ALL_APIS.length + CHART_APIS.length + DIVISIONAL_APIS.length

  const fetchAllData = useCallback(async () => {
    if (!birth.latitude || !birth.longitude) {
      toast.error('Please select a valid location')
      return
    }
    setLoading(true)
    setReportData(null)
    setProgress({ done: 0, total: totalApis, current: 'Starting...' })

    const bd = buildBirthData(birth)
    const headers = { 'X-API-Key': API_KEY, 'Content-Type': 'application/json' }
    const results = {}

    const fetchJson = async (path, body) => {
      const res = await api.post(path, body, { headers, validateStatus: () => true })
      return res.data
    }

    const fetchSvg = async (path, body) => {
      const res = await api.post(path, body, { headers, validateStatus: () => true, responseType: 'text', transformResponse: [d => d] })
      const raw = res.data
      if (typeof raw === 'string') {
        if (raw.trim().startsWith('<?xml') || raw.trim().startsWith('<svg')) return raw
        try {
          const parsed = JSON.parse(raw)
          if (parsed && parsed.svg) return parsed.svg
        } catch {}
      }
      if (raw && typeof raw === 'object' && raw.svg) return raw.svg
      return raw || ''
    }

    const fetchText = async (path, body) => {
      const res = await api.post(path, body, { headers, validateStatus: () => true, responseType: 'text', transformResponse: [d => d] })
      return res.data
    }

    try {
      // Fetch JSON APIs in batches of 6
      for (let i = 0; i < ALL_APIS.length; i += 6) {
        const batch = ALL_APIS.slice(i, i + 6)
        const promises = batch.map(async (apiDef) => {
          const body = { ...bd, ...(apiDef.extraBody || {}) }
          // Lucky endpoints only need dateOfBirth
          const isLucky = apiDef.key.startsWith('lucky')
          const reqBody = isLucky ? { dateOfBirth: bd.dateOfBirth } : body
          try {
            const data = await fetchJson(apiDef.path, reqBody)
            return { key: apiDef.key, data }
          } catch (e) {
            return { key: apiDef.key, data: { error: e.message } }
          }
        })
        const batchResults = await Promise.all(promises)
        for (const r of batchResults) {
          results[r.key] = r.data
        }
        setProgress({ done: Math.min(i + 6, ALL_APIS.length), total: totalApis, current: batch.map(b => b.key).join(', ') })
      }

      // Fetch chart SVGs in batches of 3
      for (let i = 0; i < CHART_APIS.length; i += 3) {
        const batch = CHART_APIS.slice(i, i + 3)
        const promises = batch.map(async (apiDef) => {
          try {
            const data = await fetchSvg(apiDef.path, bd)
            return { key: apiDef.key, data }
          } catch (e) {
            return { key: apiDef.key, data: '' }
          }
        })
        const batchResults = await Promise.all(promises)
        for (const r of batchResults) {
          results[r.key] = r.data
        }
        setProgress({ done: ALL_APIS.length + Math.min(i + 3, CHART_APIS.length), total: totalApis, current: 'Charts: ' + batch.map(b => b.key).join(', ') })
      }

      // Fetch divisional chart SVGs in batches of 4
      for (let i = 0; i < DIVISIONAL_APIS.length; i += 4) {
        const batch = DIVISIONAL_APIS.slice(i, i + 4)
        const promises = batch.map(async (apiDef) => {
          try {
            const data = await fetchJson(apiDef.path, { ...bd, name: apiDef.name, theme: 'light' })
            return { key: apiDef.key, data }
          } catch (e) {
            return { key: apiDef.key, data: { svg: '' } }
          }
        })
        const batchResults = await Promise.all(promises)
        for (const r of batchResults) {
          results[r.key] = r.data
        }
        setProgress({ done: ALL_APIS.length + CHART_APIS.length + Math.min(i + 4, DIVISIONAL_APIS.length), total: totalApis, current: 'Divisional: ' + batch.map(b => b.name).join(', ') })
      }

      setReportData(results)
      toast.success('Report generated successfully!')
    } catch (err) {
      toast.error('Error generating report: ' + err.message)
    } finally {
      setLoading(false)
      setProgress({ done: 0, total: 0, current: '' })
    }
  }, [birth, totalApis])

  const downloadPdf = useCallback(async () => {
    if (!reportRef.current) return
    setGeneratingPdf(true)
    try {
      const html2pdf = (await import('html2pdf.js')).default
      const element = reportRef.current
      const opt = {
        margin: [10, 10, 10, 10],
        filename: `${branding.clientName || birth.locationName || 'Kundali'}_Report.pdf`,
        image: { type: 'jpeg', quality: 0.95 },
        html2canvas: { scale: 2, useCORS: true, letterRendering: true, logging: false },
        jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
        pagebreak: { mode: ['avoid-all', 'css', 'legacy'] },
      }
      await html2pdf().set(opt).from(element).save()
      toast.success('PDF downloaded!')
    } catch (err) {
      toast.error('PDF generation failed: ' + err.message)
    } finally {
      setGeneratingPdf(false)
    }
  }, [branding, birth])

  const handlePrint = useCallback(() => {
    window.print()
  }, [])

  return (
    <div style={{ minHeight: '100vh', paddingTop: 96, paddingLeft: 24, paddingRight: 24 }}>
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} style={{ maxWidth: 1400, margin: '0 auto' }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 24 }}>
          <div>
            <h1 style={{ fontSize: 28, fontWeight: 800 }}>Kundali <span className="gradient-text">Report Generator</span></h1>
            <p style={{ color: '#94a3b8' }}>Generate a complete 55+ page Vedic birth chart report</p>
          </div>
        </div>

        {!reportData && (
          <div className="glass" style={{ borderRadius: 'var(--radius-lg)', padding: 24, marginBottom: 24 }}>
            <h3 style={{ fontSize: 16, fontWeight: 700, color: '#a78bfa', marginBottom: 16 }}>Birth Details</h3>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: 16, marginBottom: 16 }}>
              <div>
                <label style={{ display: 'block', fontSize: 12, color: '#94a3b8', marginBottom: 4 }}>Date of Birth</label>
                <input className="input-field" type="date" value={birth.dateOfBirth}
                  onChange={(e) => setBirth({ ...birth, dateOfBirth: e.target.value })} style={{ fontSize: 13 }} />
              </div>
              <div>
                <label style={{ display: 'block', fontSize: 12, color: '#94a3b8', marginBottom: 4 }}>Time of Birth</label>
                <input className="input-field" type="time" value={birth.timeOfBirth}
                  onChange={(e) => setBirth({ ...birth, timeOfBirth: e.target.value })} style={{ fontSize: 13 }} />
              </div>
              <div style={{ gridColumn: 'span 1' }}>
                <LocationSearch
                  value={birth.locationName}
                  onSelect={(loc) => setBirth({ ...birth, ...loc })}
                />
              </div>
            </div>

            {/* Branding Toggle */}
            <button onClick={() => setShowBranding(!showBranding)}
              style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '8px 16px', background: showBranding ? 'rgba(124,58,237,0.2)' : 'rgba(100,116,139,0.1)', border: 'none', borderRadius: 8, color: showBranding ? '#a78bfa' : '#94a3b8', fontSize: 13, fontWeight: 600, cursor: 'pointer', marginBottom: showBranding ? 16 : 0 }}>
              <Palette size={14} /> Branding & Customization {showBranding ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
            </button>

            {showBranding && (
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: 16, padding: '16px 0', borderTop: '1px solid rgba(100,116,139,0.15)' }}>
                <div>
                  <label style={{ display: 'block', fontSize: 12, color: '#94a3b8', marginBottom: 4 }}>Client Name</label>
                  <input className="input-field" value={branding.clientName} placeholder="e.g. Rahul Sharma"
                    onChange={(e) => setBranding({ ...branding, clientName: e.target.value })} style={{ fontSize: 13 }} />
                </div>
                <div>
                  <label style={{ display: 'block', fontSize: 12, color: '#94a3b8', marginBottom: 4 }}>Brand Name</label>
                  <input className="input-field" value={branding.brandName}
                    onChange={(e) => setBranding({ ...branding, brandName: e.target.value })} style={{ fontSize: 13 }} />
                </div>
                <div>
                  <label style={{ display: 'block', fontSize: 12, color: '#94a3b8', marginBottom: 4 }}>Logo URL</label>
                  <input className="input-field" value={branding.logoUrl} placeholder="https://..."
                    onChange={(e) => setBranding({ ...branding, logoUrl: e.target.value })} style={{ fontSize: 13 }} />
                </div>
                <div>
                  <label style={{ display: 'block', fontSize: 12, color: '#94a3b8', marginBottom: 4 }}>Cover Title</label>
                  <input className="input-field" value={branding.coverTitle}
                    onChange={(e) => setBranding({ ...branding, coverTitle: e.target.value })} style={{ fontSize: 13 }} />
                </div>
                <div>
                  <label style={{ display: 'block', fontSize: 12, color: '#94a3b8', marginBottom: 4 }}>Cover Subtitle</label>
                  <input className="input-field" value={branding.coverSubtitle}
                    onChange={(e) => setBranding({ ...branding, coverSubtitle: e.target.value })} style={{ fontSize: 13 }} />
                </div>
                <div>
                  <label style={{ display: 'block', fontSize: 12, color: '#94a3b8', marginBottom: 4 }}>Primary Color</label>
                  <div style={{ display: 'flex', gap: 8 }}>
                    <input type="color" value={branding.primaryColor}
                      onChange={(e) => setBranding({ ...branding, primaryColor: e.target.value })}
                      style={{ width: 40, height: 40, border: 'none', borderRadius: 8, cursor: 'pointer', background: 'none' }} />
                    <input className="input-field" value={branding.primaryColor}
                      onChange={(e) => setBranding({ ...branding, primaryColor: e.target.value })} style={{ fontSize: 13, flex: 1 }} />
                  </div>
                </div>
                <div>
                  <label style={{ display: 'block', fontSize: 12, color: '#94a3b8', marginBottom: 4 }}>Secondary Color</label>
                  <div style={{ display: 'flex', gap: 8 }}>
                    <input type="color" value={branding.secondaryColor}
                      onChange={(e) => setBranding({ ...branding, secondaryColor: e.target.value })}
                      style={{ width: 40, height: 40, border: 'none', borderRadius: 8, cursor: 'pointer', background: 'none' }} />
                    <input className="input-field" value={branding.secondaryColor}
                      onChange={(e) => setBranding({ ...branding, secondaryColor: e.target.value })} style={{ fontSize: 13, flex: 1 }} />
                  </div>
                </div>
                <div>
                  <label style={{ display: 'block', fontSize: 12, color: '#94a3b8', marginBottom: 4 }}>Header Text</label>
                  <input className="input-field" value={branding.headerText}
                    onChange={(e) => setBranding({ ...branding, headerText: e.target.value })} style={{ fontSize: 13 }} />
                </div>
                <div>
                  <label style={{ display: 'block', fontSize: 12, color: '#94a3b8', marginBottom: 4 }}>Footer Text</label>
                  <input className="input-field" value={branding.footerText}
                    onChange={(e) => setBranding({ ...branding, footerText: e.target.value })} style={{ fontSize: 13 }} />
                </div>
                <div style={{ gridColumn: '1 / -1' }}>
                  <label style={{ display: 'block', fontSize: 12, color: '#94a3b8', marginBottom: 4 }}>Back Page Message</label>
                  <textarea className="input-field" value={branding.backPageMessage} rows={3}
                    onChange={(e) => setBranding({ ...branding, backPageMessage: e.target.value })}
                    style={{ fontSize: 13, resize: 'vertical' }} />
                </div>
              </div>
            )}

            {/* Loading Progress */}
            {loading && (
              <div style={{ marginTop: 16, padding: 16, background: 'rgba(124,58,237,0.08)', borderRadius: 12 }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8 }}>
                  <Loader2 size={16} color="#a78bfa" style={{ animation: 'spin 1s linear infinite' }} />
                  <span style={{ fontSize: 13, color: '#e2e8f0' }}>Generating report... ({progress.done}/{progress.total})</span>
                </div>
                <div style={{ width: '100%', height: 6, background: 'rgba(100,116,139,0.2)', borderRadius: 3, overflow: 'hidden' }}>
                  <div style={{ width: `${progress.total ? (progress.done / progress.total) * 100 : 0}%`, height: '100%', background: 'linear-gradient(90deg, #7c3aed, #ec4899)', borderRadius: 3, transition: 'width 0.3s ease' }} />
                </div>
                <div style={{ fontSize: 11, color: '#64748b', marginTop: 6 }}>{progress.current}</div>
              </div>
            )}

            <button className="btn-primary" onClick={fetchAllData} disabled={loading}
              style={{ width: '100%', justifyContent: 'center', marginTop: 16 }}>
              {loading ? <><Loader2 size={16} style={{ animation: 'spin 1s linear infinite' }} /> Generating...</> : <><FileText size={16} /> Generate Complete Report</>}
            </button>
          </div>
        )}

        {/* Report Preview + Actions */}
        {reportData && (
          <>
            {/* Action bar - hidden in print */}
            <div className="no-print" style={{ display: 'flex', gap: 12, marginBottom: 20, flexWrap: 'wrap' }}>
              <button className="btn-primary" onClick={downloadPdf} disabled={generatingPdf}>
                {generatingPdf ? <><Loader2 size={16} style={{ animation: 'spin 1s linear infinite' }} /> Generating PDF...</> : <><Download size={16} /> Download PDF</>}
              </button>
              <button className="btn-secondary" onClick={handlePrint}>
                <Settings size={16} /> Print / Save as PDF
              </button>
              <button className="btn-secondary" onClick={() => { setReportData(null) }}>
                <FileText size={16} /> New Report
              </button>
            </div>

            {/* The Report */}
            <div ref={reportRef}>
              <ReportTemplate data={reportData} branding={branding} />
            </div>

            {/* Bottom actions - hidden in print */}
            <div className="no-print" style={{ display: 'flex', gap: 12, marginTop: 20, marginBottom: 40, justifyContent: 'center' }}>
              <button className="btn-primary" onClick={downloadPdf} disabled={generatingPdf}>
                {generatingPdf ? <><Loader2 size={16} style={{ animation: 'spin 1s linear infinite' }} /> Generating PDF...</> : <><Download size={16} /> Download PDF</>}
              </button>
              <button className="btn-secondary" onClick={() => { setReportData(null) }}>
                Generate New Report
              </button>
            </div>
          </>
        )}
      </motion.div>
    </div>
  )
}
