// ──── Field Templates ────
const birthFields = (extra = []) => [
  { key: 'dateOfBirth', label: 'Date of Birth', type: 'date', group: 'Birth Data' },
  { key: 'timeOfBirth', label: 'Time of Birth', type: 'time', group: 'Birth Data' },
  { key: '_location', label: 'Birth Location', type: 'location', group: 'Birth Data' },
  ...extra,
]

const partnerBirthFields = (extra = []) => [
  { key: 'dateOfBirth', label: 'Your Date of Birth', type: 'date', group: 'Your Data' },
  { key: 'timeOfBirth', label: 'Your Time of Birth', type: 'time', group: 'Your Data' },
  { key: '_location', label: 'Your Location', type: 'location', group: 'Your Data' },
  { key: 'partnerDateOfBirth', label: 'Partner Date of Birth', type: 'date', group: 'Partner Data' },
  { key: 'partnerTimeOfBirth', label: 'Partner Time of Birth', type: 'time', group: 'Partner Data' },
  { key: '_partnerLocation', label: 'Partner Location', type: 'location', group: 'Partner Data' },
  ...extra,
]

const coupleBirthFields = (extra = []) => [
  { key: 'maleDateOfBirth', label: 'Male Date of Birth', type: 'date', group: 'Male Data' },
  { key: 'maleTimeOfBirth', label: 'Male Time of Birth', type: 'time', group: 'Male Data' },
  { key: '_maleLocation', label: 'Male Location', type: 'location', group: 'Male Data' },
  { key: 'femaleDateOfBirth', label: 'Female Date of Birth', type: 'date', group: 'Female Data' },
  { key: 'femaleTimeOfBirth', label: 'Female Time of Birth', type: 'time', group: 'Female Data' },
  { key: '_femaleLocation', label: 'Female Location', type: 'location', group: 'Female Data' },
  ...extra,
]

const muhuratFields = (extra = []) => [
  { key: 'dateOfBirth', label: 'Date', type: 'date', group: 'Date' },
  { key: '_location', label: 'Location', type: 'location', group: 'Location' },
  ...extra,
]

const yearFields = (extra = []) => [
  { key: 'year', label: 'Year', type: 'number', group: 'Year' },
  { key: '_location', label: 'Location', type: 'location', group: 'Location', optional: true },
  ...extra,
]

const calendarFields = (extra = []) => [
  { key: 'year', label: 'Year', type: 'number', group: 'Date' },
  { key: 'month', label: 'Month', type: 'number', group: 'Date', min: 1, max: 12 },
  { key: '_location', label: 'Location', type: 'location', group: 'Location' },
  ...extra,
]

const D = '1990-05-15'
const T = '10:30'

// ──── Endpoint Definitions ────
export const endpointCategories = {
  'Charts & Kundli': [
    { method: 'POST', path: '/api/kundli', label: 'Birth Chart (Kundli)', fields: birthFields([{ key: 'tropical', label: 'Tropical Zodiac', type: 'select', options: ['false', 'true'], group: 'Zodiac' }]) },
    { method: 'POST', path: '/chart/svg', label: 'North Indian Diamond SVG', fields: birthFields([{ key: 'theme', label: 'Theme', type: 'select', options: ['dark', 'light'], group: 'Style' }]) },
    { method: 'POST', path: '/chart/grid-svg', label: 'Grid Chart SVG', fields: birthFields([{ key: 'theme', label: 'Theme', type: 'select', options: ['dark', 'light'], group: 'Style' }]) },
    { method: 'POST', path: '/chart/east-svg', label: 'East Indian SVG', fields: birthFields([{ key: 'theme', label: 'Theme', type: 'select', options: ['dark', 'light'], group: 'Style' }]) },
    { method: 'POST', path: '/chart/moon-svg', label: 'Moon Chart SVG', fields: birthFields([{ key: 'theme', label: 'Theme', type: 'select', options: ['dark', 'light'], group: 'Style' }]) },
    { method: 'POST', path: '/chart/navamsa-svg', label: 'Navamsa (D9) SVG', fields: birthFields([{ key: 'theme', label: 'Theme', type: 'select', options: ['dark', 'light'], group: 'Style' }]) },
    { method: 'POST', path: '/chart/hora-svg', label: 'Hora (D2) SVG', fields: birthFields([{ key: 'theme', label: 'Theme', type: 'select', options: ['dark', 'light'], group: 'Style' }]) },
    { method: 'POST', path: '/chart/sudarshana-svg', label: 'Sudarshana Chakra SVG', fields: birthFields([{ key: 'theme', label: 'Theme', type: 'select', options: ['dark', 'light'], group: 'Style' }]) },
    { method: 'POST', path: '/chart/divisional-svg?d=1', label: 'D1 Rasi (General Life)', fields: birthFields([{ key: 'name', label: 'Division', type: 'select', options: ['D1','D2','D3','D4','D5','D6','D7','D8','D9','D10','D11','D12','D16','D20','D24','D27','D30','D40','D45','D60'], group: 'Chart' }, { key: 'theme', label: 'Theme', type: 'select', options: ['dark', 'light'], group: 'Style' }]) },
    { method: 'POST', path: '/chart/divisional-svg?d=9', label: 'D9 Navamsa (Marriage)', fields: birthFields([{ key: 'name', label: 'Division', type: 'select', options: ['D1','D2','D3','D4','D5','D6','D7','D8','D9','D10','D11','D12','D16','D20','D24','D27','D30','D40','D45','D60'], group: 'Chart' }, { key: 'theme', label: 'Theme', type: 'select', options: ['dark', 'light'], group: 'Style' }]) },
    { method: 'POST', path: '/chart/divisional-svg?d=10', label: 'D10 Dashamamsa (Career)', fields: birthFields([{ key: 'name', label: 'Division', type: 'select', options: ['D1','D2','D3','D4','D5','D6','D7','D8','D9','D10','D11','D12','D16','D20','D24','D27','D30','D40','D45','D60'], group: 'Chart' }, { key: 'theme', label: 'Theme', type: 'select', options: ['dark', 'light'], group: 'Style' }]) },
  ],
  Horoscope: [
    { method: 'POST', path: '/horoscope/daily', label: 'Daily Horoscope', fields: birthFields() },
    { method: 'POST', path: '/horoscope/weekly', label: 'Weekly Horoscope', fields: birthFields() },
    { method: 'POST', path: '/horoscope/monthly', label: 'Monthly Horoscope', fields: birthFields() },
    { method: 'POST', path: '/horoscope/yearly', label: 'Yearly Horoscope', fields: birthFields() },
    { method: 'POST', path: '/horoscope/career', label: 'Career Horoscope', fields: birthFields() },
    { method: 'POST', path: '/horoscope/love', label: 'Love Horoscope', fields: birthFields() },
    { method: 'POST', path: '/horoscope/finance', label: 'Finance Horoscope', fields: birthFields() },
    { method: 'POST', path: '/horoscope/health', label: 'Health Horoscope', fields: birthFields() },
    { method: 'POST', path: '/horoscope/business', label: 'Business Prediction', fields: birthFields() },
    { method: 'POST', path: '/horoscope/education', label: 'Education Prediction', fields: birthFields() },
    { method: 'POST', path: '/horoscope/child', label: 'Child Prediction', fields: birthFields() },
    { method: 'POST', path: '/horoscope/foreign', label: 'Foreign Travel/Settlement', fields: birthFields() },
  ],
  Dasha: [
    { method: 'POST', path: '/horoscope/dasha/vimshottari', label: 'Vimshottari Dasha', fields: birthFields() },
    { method: 'POST', path: '/horoscope/dasha/current', label: 'Current Dasha', fields: birthFields() },
    { method: 'POST', path: '/horoscope/dasha/details', label: 'Dasha Details', fields: birthFields([{ key: 'planet', label: 'Planet', type: 'select', options: ['Sun','Moon','Mars','Mercury','Jupiter','Venus','Saturn','Rahu','Ketu'], group: 'Dasha' }]) },
    { method: 'POST', path: '/horoscope/dasha/timeline', label: 'Dasha Timeline', fields: birthFields([{ key: 'startYear', label: 'Start Year', type: 'number', group: 'Range' }, { key: 'endYear', label: 'End Year', type: 'number', group: 'Range' }]) },
    { method: 'POST', path: '/horoscope/dasha/chara', label: 'Chara Dasha (Jaimini)', fields: birthFields() },
    { method: 'POST', path: '/dasha/yogini', label: 'Yogini Dasha', fields: birthFields() },
    { method: 'POST', path: '/dasha/kalachakra', label: 'Kalachakra Dasha', fields: birthFields() },
    { method: 'POST', path: '/dasha/ashtottari', label: 'Ashtottari Dasha', fields: birthFields() },
  ],
  Panchang: [
    { method: 'POST', path: '/horoscope/panchang', label: 'Panchang', fields: birthFields() },
    { method: 'POST', path: '/horoscope/panchang/rahu-kaal', label: 'Rahu Kaal', fields: birthFields() },
    { method: 'POST', path: '/horoscope/panchang/gulika-kaal', label: 'Gulika Kaal', fields: birthFields() },
    { method: 'POST', path: '/horoscope/panchang/yamaganda', label: 'Yamaganda', fields: birthFields() },
    { method: 'POST', path: '/horoscope/panchang/choghadiya', label: 'Choghadiya', fields: birthFields() },
    { method: 'POST', path: '/horoscope/panchang/hora', label: 'Hora', fields: birthFields() },
    { method: 'POST', path: '/horoscope/panchang/moonrise', label: 'Moonrise', fields: birthFields() },
    { method: 'POST', path: '/horoscope/panchang/moonset', label: 'Moonset', fields: birthFields() },
    { method: 'POST', path: '/horoscope/panchang/abhijit-muhurat', label: 'Abhijit Muhurat', fields: birthFields() },
    { method: 'POST', path: '/horoscope/panchang/panchaka', label: 'Panchaka', fields: birthFields() },
    { method: 'POST', path: '/horoscope/panchang/gulika-position', label: 'Gulika Position', fields: birthFields() },
    { method: 'POST', path: '/horoscope/panchang/roga-nidana', label: 'Roga Nidana', fields: birthFields() },
  ],
  Transit: [
    { method: 'POST', path: '/horoscope/transit', label: 'Transit', fields: birthFields() },
    { method: 'POST', path: '/horoscope/transit/current', label: 'Current Transit', fields: birthFields() },
    { method: 'POST', path: '/horoscope/transit/prediction', label: 'Transit Prediction', fields: birthFields() },
    { method: 'POST', path: '/horoscope/transit/by-planet', label: 'Transit by Planet', fields: birthFields([{ key: 'planet', label: 'Planet', type: 'select', options: ['Sun','Moon','Mars','Mercury','Jupiter','Venus','Saturn','Rahu','Ketu'], group: 'Transit' }]) },
    { method: 'POST', path: '/horoscope/transit/monthly', label: 'Monthly Transit Report', fields: birthFields() },
    { method: 'POST', path: '/horoscope/transit/timing', label: 'Transit Timing', fields: birthFields([{ key: 'event', label: 'Event', type: 'select', options: ['marriage','career','education','foreign-travel','children','property','health','business'], group: 'Event' }]) },
    { method: 'POST', path: '/api/transit/planet-transit', label: 'Planet Transit Detail', fields: birthFields([{ key: 'planetName', label: 'Planet', type: 'select', options: ['Sun','Moon','Mars','Mercury','Jupiter','Venus','Saturn','Rahu','Ketu'], group: 'Planet' }]) },
    { method: 'POST', path: '/api/transit/retrograde', label: 'Retrograde', fields: birthFields() },
    { method: 'POST', path: '/api/transit/combust', label: 'Combust', fields: birthFields() },
    { method: 'POST', path: '/api/transit/exalted', label: 'Exalted Planets', fields: birthFields() },
    { method: 'POST', path: '/api/transit/debilitated', label: 'Debilitated Planets', fields: birthFields() },
    { method: 'POST', path: '/api/transit/aspect', label: 'Transit Aspects', fields: birthFields() },
  ],
  Compatibility: [
    { method: 'POST', path: '/horoscope/compat', label: 'Ashtakoot Milan', fields: coupleBirthFields() },
    { method: 'POST', path: '/horoscope/compat/detailed', label: 'Detailed Compatibility', fields: coupleBirthFields() },
    { method: 'POST', path: '/api/compat/gun-milan', label: 'Gun Milan', fields: coupleBirthFields() },
    { method: 'POST', path: '/api/compat/nadi', label: 'Nadi Dosha Check', fields: coupleBirthFields() },
    { method: 'POST', path: '/api/compat/bhakoot', label: 'Bhakoot Check', fields: coupleBirthFields() },
    { method: 'POST', path: '/api/compat/yoni', label: 'Yoni Match', fields: coupleBirthFields() },
    { method: 'POST', path: '/api/compat/gana', label: 'Gana Match', fields: coupleBirthFields() },
    { method: 'POST', path: '/api/compat/tara', label: 'Tara Match', fields: coupleBirthFields() },
  ],
  Dosha: [
    { method: 'POST', path: '/horoscope/dosha/compute', label: 'Compute Doshas', fields: birthFields() },
    { method: 'POST', path: '/horoscope/dosha/remedies', label: 'Dosha Remedies', fields: birthFields() },
    { method: 'POST', path: '/horoscope/dosha/severity', label: 'Dosha Severity', fields: birthFields() },
    { method: 'POST', path: '/horoscope/dosha/compatibility-impact', label: 'Dosha Compatibility Impact', fields: partnerBirthFields() },
    { method: 'POST', path: '/api/dosha/grahan', label: 'Grahan Dosha', fields: birthFields() },
    { method: 'POST', path: '/api/dosha/shrapit', label: 'Shrapit Dosha', fields: birthFields() },
    { method: 'POST', path: '/api/dosha/manglik-detailed', label: 'Manglik Detailed', fields: birthFields() },
    { method: 'POST', path: '/api/dosha/nadi-dosha', label: 'Nadi Dosha', fields: coupleBirthFields() },
    { method: 'POST', path: '/api/dosha/bhakoot-dosha', label: 'Bhakoot Dosha', fields: coupleBirthFields() },
    { method: 'POST', path: '/api/dosha/yoni-compatibility', label: 'Yoni Compatibility', fields: coupleBirthFields() },
    { method: 'POST', path: '/horoscope/dosha/dhaiya', label: 'Dhaiya & Sade Sati', fields: birthFields() },
    { method: 'POST', path: '/yogini/dosha', label: 'Yogini Dosha', fields: birthFields() },
  ],
  Yoga: [
    { method: 'POST', path: '/horoscope/yoga/predictions', label: 'Yoga Predictions', fields: birthFields() },
    { method: 'POST', path: '/horoscope/yoga/detailed', label: 'Detailed Yoga', fields: birthFields([{ key: 'yogaName', label: 'Yoga Name', type: 'text', placeholder: 'e.g. Gajakesari', group: 'Yoga' }]) },
    { method: 'POST', path: '/horoscope/yoga/score', label: 'Yoga Score', fields: birthFields() },
  ],
  Bhava: [
    { method: 'POST', path: '/horoscope/bhava-chalit', label: 'Bhava Chalit', fields: birthFields() },
    { method: 'POST', path: '/horoscope/bhava-chalit/compare', label: 'Bhava Compare', fields: birthFields() },
    { method: 'POST', path: '/horoscope/bhava-chalit/cusps', label: 'Bhava Cusps', fields: birthFields() },
  ],
  Muhurat: [
    { method: 'POST', path: '/horoscope/muhurat/marriage', label: 'Marriage Muhurat', fields: muhuratFields() },
    { method: 'POST', path: '/horoscope/muhurat/vehicle-purchase', label: 'Vehicle Purchase', fields: muhuratFields() },
    { method: 'POST', path: '/horoscope/muhurat/house-warming', label: 'House Warming', fields: muhuratFields() },
    { method: 'POST', path: '/horoscope/muhurat/property-purchase', label: 'Property Purchase', fields: muhuratFields() },
    { method: 'POST', path: '/horoscope/muhurat/business-opening', label: 'Business Opening', fields: muhuratFields() },
    { method: 'POST', path: '/horoscope/muhurat/naming-ceremony', label: 'Naming Ceremony', fields: muhuratFields() },
    { method: 'POST', path: '/horoscope/muhurat/griha-pravesh', label: 'Griha Pravesh', fields: muhuratFields() },
    { method: 'POST', path: '/horoscope/muhurat/engagement', label: 'Engagement', fields: muhuratFields() },
    { method: 'POST', path: '/horoscope/muhurat/cesarean', label: 'Cesarean Muhurat', fields: birthFields() },
  ],
  Varshaphal: [
    { method: 'POST', path: '/horoscope/varshaphal', label: 'Varshaphal (Annual)', fields: birthFields([{ key: 'year', label: 'Year', type: 'number', group: 'Year' }]) },
    { method: 'POST', path: '/horoscope/varshaphal/prediction', label: 'Varshaphal Prediction', fields: birthFields([{ key: 'year', label: 'Year', type: 'number', group: 'Year' }]) },
    { method: 'POST', path: '/horoscope/varshaphal/tajika-aspects', label: 'Tajika Aspects', fields: birthFields([{ key: 'year', label: 'Year', type: 'number', group: 'Year' }]) },
  ],
  Prashna: [
    { method: 'POST', path: '/api/prashna/chart', label: 'Prashna Chart', fields: birthFields([{ key: 'question', label: 'Question', type: 'textarea', placeholder: 'Ask your question...', group: 'Question' }]) },
    { method: 'POST', path: '/api/prashna/judgement', label: 'Prashna Judgement', fields: birthFields([{ key: 'question', label: 'Question', type: 'textarea', placeholder: 'Ask your question...', group: 'Question' }]) },
  ],
  Calculator: [
    { method: 'POST', path: '/api/calculator/lagna', label: 'Lagna Calculator', fields: birthFields() },
    { method: 'POST', path: '/api/calculator/moon-sign', label: 'Moon Sign', fields: birthFields() },
    { method: 'POST', path: '/api/calculator/sun-sign', label: 'Sun Sign', fields: birthFields() },
    { method: 'POST', path: '/api/calculator/planet-strength', label: 'Planet Strength', fields: birthFields() },
    { method: 'POST', path: '/api/calculator/shadbala', label: 'Shadbala', fields: birthFields() },
    { method: 'POST', path: '/api/calculator/ashtakavarga', label: 'Ashtakavarga', fields: birthFields() },
  ],
  Gemstone: [
    { method: 'POST', path: '/api/gemstone/recommendation', label: 'Recommendation', fields: birthFields() },
    { method: 'POST', path: '/api/gemstone/by-planet', label: 'By Planet', fields: [{ key: 'planet', label: 'Planet', type: 'select', options: ['Sun','Moon','Mars','Mercury','Jupiter','Venus','Saturn','Rahu','Ketu'], group: 'Planet' }, { key: 'bodyWeightKg', label: 'Body Weight (kg)', type: 'number', min: 30, group: 'Physical' }] },
    { method: 'POST', path: '/api/gemstone/by-lagna', label: 'By Lagna', fields: birthFields() },
    { method: 'POST', path: '/api/gemstone/by-dasha', label: 'By Dasha', fields: birthFields() },
    { method: 'POST', path: '/api/gemstone/wearing', label: 'Wearing Guide', fields: birthFields() },
    { method: 'POST', path: '/api/gemstone/weight', label: 'Weight Calculator', fields: birthFields([{ key: 'bodyWeightKg', label: 'Body Weight (kg)', type: 'number', group: 'Physical' }]) },
    { method: 'POST', path: '/api/gemstone/metal', label: 'Metal Guide', fields: birthFields() },
    { method: 'POST', path: '/api/gemstone/finger', label: 'Finger Guide', fields: birthFields() },
  ],
  Rudraksha: [
    { method: 'POST', path: '/api/rudraksha/recommendation', label: 'Recommendation', fields: birthFields() },
    { method: 'POST', path: '/api/rudraksha/mukhi-identification', label: 'Mukhi Identification', fields: [{ key: 'description', label: 'Description', type: 'textarea', placeholder: 'Describe the Rudraksha...', group: 'Details' }, { key: 'visualFeatures', label: 'Visual Features', type: 'text', placeholder: 'e.g. Dark brown, 5 lines visible', group: 'Details' }] },
    { method: 'POST', path: '/api/rudraksha/wearing-method', label: 'Wearing Method', fields: [{ key: 'mukhiCount', label: 'Mukhi Count', type: 'number', min: 1, group: 'Details' }, { key: 'gender', label: 'Gender', type: 'select', options: ['male', 'female'], group: 'Details' }] },
    { method: 'POST', path: '/api/rudraksha/mantra', label: 'Mantra', fields: [{ key: 'mukhiCount', label: 'Mukhi Count', type: 'number', min: 1, group: 'Details' }] },
    { method: 'POST', path: '/api/rudraksha/benefits', label: 'Benefits', fields: [{ key: 'mukhiCount', label: 'Mukhi Count', type: 'number', min: 1, group: 'Details' }] },
  ],
  Numerology: [
    { method: 'POST', path: '/api/numerology/life-path', label: 'Life Path Number', fields: [{ key: 'dateOfBirth', label: 'Date of Birth', type: 'date', group: 'Details' }] },
    { method: 'POST', path: '/api/numerology/destiny', label: 'Destiny Number', fields: [{ key: 'fullName', label: 'Full Name', type: 'text', placeholder: 'e.g. Rahul Sharma', group: 'Details' }] },
    { method: 'POST', path: '/api/numerology/soul', label: 'Soul Number', fields: [{ key: 'fullName', label: 'Full Name', type: 'text', placeholder: 'e.g. Rahul Sharma', group: 'Details' }] },
    { method: 'POST', path: '/api/numerology/expression', label: 'Expression Number', fields: [{ key: 'fullName', label: 'Full Name', type: 'text', placeholder: 'e.g. Rahul Sharma', group: 'Details' }] },
    { method: 'POST', path: '/api/numerology/mobile', label: 'Mobile Number', fields: [{ key: 'mobileNumber', label: 'Mobile Number', type: 'text', placeholder: 'e.g. 9876543210', group: 'Details' }] },
    { method: 'POST', path: '/api/numerology/vehicle', label: 'Vehicle Number', fields: [{ key: 'vehicleNumber', label: 'Vehicle Number', type: 'text', placeholder: 'e.g. DL01AB1234', group: 'Details' }] },
    { method: 'POST', path: '/api/numerology/business-name', label: 'Business Name', fields: [{ key: 'businessName', label: 'Business Name', type: 'text', placeholder: 'e.g. Celestial Solutions', group: 'Details' }, { key: 'dateOfBirth', label: 'Date of Birth', type: 'date', group: 'Details' }] },
    { method: 'POST', path: '/api/numerology/baby-name', label: 'Baby Name', fields: [{ key: 'dateOfBirth', label: 'Date of Birth', type: 'date', group: 'Details' }, { key: 'gender', label: 'Gender', type: 'select', options: ['male', 'female'], group: 'Details' }, { key: 'parentName', label: 'Parent Name', type: 'text', group: 'Details' }] },
    { method: 'POST', path: '/api/numerology/name-number', label: 'Name Number', fields: [{ key: 'name', label: 'Name', type: 'text', placeholder: 'e.g. Rahul Sharma', group: 'Details' }] },
    { method: 'POST', path: '/api/numerology/name-compatibility', label: 'Name Compatibility', fields: [{ key: 'name1', label: 'Name 1', type: 'text', group: 'Details' }, { key: 'name2', label: 'Name 2', type: 'text', group: 'Details' }] },
  ],
  Festival: [
    { method: 'POST', path: '/api/festival/hindu-festival', label: 'Hindu Festivals', fields: [{ key: 'year', label: 'Year', type: 'number', group: 'Details' }] },
    { method: 'POST', path: '/api/festival/ekadashi', label: 'Ekadashi', fields: [{ key: 'year', label: 'Year', type: 'number', group: 'Details' }] },
    { method: 'POST', path: '/api/festival/sankranti', label: 'Sankranti', fields: [{ key: 'year', label: 'Year', type: 'number', group: 'Details' }] },
    { method: 'POST', path: '/api/festival/purnima', label: 'Purnima', fields: [{ key: 'year', label: 'Year', type: 'number', group: 'Details' }] },
    { method: 'POST', path: '/api/festival/amavasya', label: 'Amavasya', fields: [{ key: 'year', label: 'Year', type: 'number', group: 'Details' }] },
    { method: 'POST', path: '/api/festival/chaturthi', label: 'Chaturthi', fields: [{ key: 'year', label: 'Year', type: 'number', group: 'Details' }] },
    { method: 'POST', path: '/api/festival/navratri', label: 'Navratri', fields: [{ key: 'year', label: 'Year', type: 'number', group: 'Details' }] },
    { method: 'POST', path: '/api/festival/diwali', label: 'Diwali', fields: [{ key: 'year', label: 'Year', type: 'number', group: 'Details' }] },
    { method: 'POST', path: '/api/festival/holi', label: 'Holi', fields: [{ key: 'year', label: 'Year', type: 'number', group: 'Details' }] },
  ],
  Calendar: [
    { method: 'POST', path: '/api/calendar/hindu', label: 'Hindu Calendar', fields: calendarFields() },
    { method: 'POST', path: '/api/calendar/panchang', label: 'Calendar Panchang', fields: calendarFields() },
    { method: 'POST', path: '/api/calendar/festival', label: 'Calendar Festivals', fields: [{ key: 'year', label: 'Year', type: 'number', group: 'Details' }] },
    { method: 'POST', path: '/api/calendar/muhurat', label: 'Calendar Muhurat', fields: calendarFields() },
    { method: 'POST', path: '/calendar-api/hindu', label: 'Calendar API Hindu', fields: calendarFields() },
    { method: 'POST', path: '/calendar-api/panchang', label: 'Calendar API Panchang', fields: calendarFields() },
    { method: 'POST', path: '/calendar-api/festival', label: 'Calendar API Festival', fields: [{ key: 'year', label: 'Year', type: 'number', group: 'Details' }] },
    { method: 'POST', path: '/calendar-api/muhurat', label: 'Calendar API Muhurat', fields: calendarFields([{ key: 'activity', label: 'Activity', type: 'select', options: ['marriage','house-warming','vehicle-purchase','business-opening','engagement','naming-ceremony'], group: 'Activity' }]) },
    { method: 'POST', path: '/api/calendar/year', label: 'Year Calendar', fields: yearFields() },
    { method: 'POST', path: '/api/calendar/year/monthly-summary', label: 'Monthly Summary', fields: yearFields([{ key: 'month', label: 'Month', type: 'number', min: 1, max: 12, group: 'Month' }]) },
    { method: 'POST', path: '/api/calendar/year/auspicious-dates', label: 'Auspicious Dates', fields: yearFields([{ key: 'purpose', label: 'Purpose', type: 'select', options: ['marriage','house-warming','vehicle-purchase','business-opening','engagement','travel','education'], group: 'Purpose' }]) },
  ],
  Pooja: [
    { method: 'POST', path: '/pooja/recommendation', label: 'Recommendation', fields: birthFields() },
    { method: 'POST', path: '/pooja/temple', label: 'Temple Suggestion', fields: birthFields() },
    { method: 'POST', path: '/pooja/sankalp', label: 'Sankalp', fields: birthFields() },
    { method: 'POST', path: '/pooja/booking', label: 'Booking', fields: birthFields([{ key: 'poojaName', label: 'Pooja Name', type: 'text', group: 'Booking' }, { key: 'name', label: 'Your Name', type: 'text', group: 'Booking' }, { key: 'phone', label: 'Phone', type: 'text', group: 'Booking' }, { key: 'email', label: 'Email', type: 'text', group: 'Booking' }]) },
    { method: 'POST', path: '/pooja/availability', label: 'Availability', fields: [{ key: 'date', label: 'Date', type: 'date', group: 'Details' }, { key: 'poojaName', label: 'Pooja Name', type: 'text', group: 'Details' }, { key: 'location', label: 'Location', type: 'text', placeholder: 'e.g. Delhi', group: 'Details' }] },
  ],
  Reports: [
    { method: 'POST', path: '/reports/full-pdf', label: 'Full Kundli PDF Report', pdf: true, fields: birthFields([{ key: 'clientName', label: 'Client Name', type: 'text', group: 'Report' }, { key: 'reportTitle', label: 'Report Title', type: 'text', group: 'Report' }, { key: 'brandName', label: 'Brand Name', type: 'text', group: 'Report' }, { key: 'contactMobile', label: 'Contact Mobile', type: 'text', group: 'Report' }, { key: 'contactEmail', label: 'Contact Email', type: 'text', group: 'Report' }, { key: 'contactWebsite', label: 'Contact Website', type: 'text', group: 'Report' }]) },
    { method: 'POST', path: '/reports/pdf-info', label: 'PDF Report Info', fields: birthFields([{ key: 'clientName', label: 'Client Name', type: 'text', group: 'Report' }]) },
    { method: 'POST', path: '/reports/birth-chart', label: 'Birth Chart Report', fields: birthFields() },
    { method: 'POST', path: '/reports/predictions', label: 'Predictions Report', fields: birthFields() },
    { method: 'POST', path: '/reports/career', label: 'Career Report', fields: birthFields() },
    { method: 'POST', path: '/reports/comprehensive', label: 'Comprehensive Report', fields: birthFields() },
  ],
  AI: [
    { method: 'POST', path: '/ai/chat', label: 'AI Chat', ai: true, fields: birthFields([{ key: 'question', label: 'Question', type: 'textarea', placeholder: 'What does my birth chart reveal about my career?', group: 'Question' }]) },
    { method: 'POST', path: '/ai/kundli-interpretation', label: 'Kundli Interpretation', ai: true, fields: birthFields() },
    { method: 'POST', path: '/ai/horoscope-generation', label: 'Horoscope Generation', ai: true, fields: birthFields() },
    { method: 'POST', path: '/ai/remedies', label: 'AI Remedies', ai: true, fields: birthFields() },
    { method: 'POST', path: '/ai/prediction', label: 'AI Prediction', ai: true, fields: birthFields() },
    { method: 'POST', path: '/ai/gemstone-advisor', label: 'AI Gemstone Advisor', ai: true, fields: birthFields() },
    { method: 'POST', path: '/ai/career-analysis', label: 'AI Career Analysis', ai: true, fields: birthFields() },
    { method: 'POST', path: '/ai/marriage-analysis', label: 'AI Marriage Analysis', ai: true, fields: partnerBirthFields() },
  ],
  Utility: [
    { method: 'POST', path: '/api/utility/ayanamsa', label: 'Ayanamsa', fields: [{ key: 'date', label: 'Date', type: 'date', group: 'Details' }, { key: 'time', label: 'Time', type: 'time', group: 'Details' }, { key: 'timezone', label: 'Timezone', type: 'text', placeholder: 'Asia/Kolkata', group: 'Details' }] },
    { method: 'POST', path: '/api/utility/ephemeris', label: 'Ephemeris', fields: [{ key: 'date', label: 'Date', type: 'date', group: 'Details' }, { key: 'time', label: 'Time', type: 'time', group: 'Details' }, { key: 'timezone', label: 'Timezone', type: 'text', placeholder: 'Asia/Kolkata', group: 'Details' }] },
    { method: 'POST', path: '/api/utility/planet-speed', label: 'Planet Speed', fields: [{ key: 'date', label: 'Date', type: 'date', group: 'Details' }, { key: 'time', label: 'Time', type: 'time', group: 'Details' }, { key: 'timezone', label: 'Timezone', type: 'text', placeholder: 'Asia/Kolkata', group: 'Details' }] },
    { method: 'POST', path: '/api/utility/lunar-phase', label: 'Lunar Phase', fields: [{ key: 'date', label: 'Date', type: 'date', group: 'Details' }, { key: 'time', label: 'Time', type: 'time', group: 'Details' }, { key: 'timezone', label: 'Timezone', type: 'text', placeholder: 'Asia/Kolkata', group: 'Details' }] },
    { method: 'POST', path: '/api/utility/eclipse', label: 'Eclipse', fields: [{ key: 'date', label: 'Date', type: 'date', group: 'Details' }, { key: 'time', label: 'Time', type: 'time', group: 'Details' }, { key: 'timezone', label: 'Timezone', type: 'text', placeholder: 'Asia/Kolkata', group: 'Details' }, { key: 'rangeDays', label: 'Range (Days)', type: 'number', group: 'Search' }] },
    { method: 'POST', path: '/api/utility/sunrise-sunset', label: 'Sunrise/Sunset', fields: [{ key: 'date', label: 'Date', type: 'date', group: 'Details' }, { key: '_location', label: 'Location', type: 'location', group: 'Location' }] },
    { method: 'POST', path: '/api/utility/julian-day', label: 'Julian Day', fields: [{ key: 'date', label: 'Date', type: 'date', group: 'Details' }, { key: 'time', label: 'Time', type: 'time', group: 'Details' }, { key: 'timezone', label: 'Timezone', type: 'text', placeholder: 'Asia/Kolkata', group: 'Details' }] },
    { method: 'POST', path: '/api/utility/rectify', label: 'Birth Rectification', fields: birthFields([{ key: 'knownAscendant', label: 'Known Ascendant', type: 'select', options: ['Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'], group: 'Known' }]) },
    { method: 'POST', path: '/api/utility/ascendant-scan', label: 'Ascendant Scan', fields: birthFields() },
    { method: 'POST', path: '/api/utility/transit-verify', label: 'Transit Verify', fields: birthFields([{ key: 'eventDate', label: 'Event Date', type: 'date', group: 'Event' }, { key: 'eventType', label: 'Event Type', type: 'select', options: ['marriage','career','education','foreign-travel','children','property','health','business'], group: 'Event' }]) },
  ],
  Location: [
    { method: 'GET', path: '/api/location/search?q=Delhi&limit=5', label: 'Search Location', get: true, fields: [{ key: 'q', label: 'Search Query', type: 'text', placeholder: 'e.g. Delhi, Mumbai, New York', group: 'Search' }, { key: 'limit', label: 'Limit', type: 'number', group: 'Search' }] },
    { method: 'GET', path: '/api/location/reverse?lat=28.6139&lon=77.209', label: 'Reverse Geocode', get: true, fields: [{ key: 'lat', label: 'Latitude', type: 'number', group: 'Coordinates' }, { key: 'lon', label: 'Longitude', type: 'number', group: 'Coordinates' }] },
    { method: 'GET', path: '/api/location/timezone?lat=28.6139&lon=77.209', label: 'Timezone Lookup', get: true, fields: [{ key: 'lat', label: 'Latitude', type: 'number', group: 'Coordinates' }, { key: 'lon', label: 'Longitude', type: 'number', group: 'Coordinates' }] },
    { method: 'GET', path: '/api/location/popular?country=IN', label: 'Popular Locations', get: true, fields: [{ key: 'country', label: 'Country Code', type: 'text', placeholder: 'e.g. IN, US, GB', group: 'Search' }] },
  ],
  Lucky: [
    { method: 'POST', path: '/lucky/color', label: 'Lucky Color', fields: [{ key: 'dateOfBirth', label: 'Date of Birth', type: 'date', group: 'Details' }] },
    { method: 'POST', path: '/lucky/number', label: 'Lucky Number', fields: [{ key: 'dateOfBirth', label: 'Date of Birth', type: 'date', group: 'Details' }] },
    { method: 'POST', path: '/lucky/day', label: 'Lucky Day', fields: [{ key: 'dateOfBirth', label: 'Date of Birth', type: 'date', group: 'Details' }] },
    { method: 'POST', path: '/lucky/metal', label: 'Lucky Metal', fields: [{ key: 'dateOfBirth', label: 'Date of Birth', type: 'date', group: 'Details' }] },
  ],
  'Lal Kitab': [
    { method: 'POST', path: '/lal-kitab/house-significations', label: 'House Significations', fields: [] },
    { method: 'POST', path: '/lal-kitab/planet-interpretations', label: 'Planet Interpretations', fields: [] },
    { method: 'POST', path: '/lal-kitab/chart-analysis', label: 'Chart Analysis', fields: birthFields() },
  ],
  'KP Astrology': [
    { method: 'POST', path: '/kp/planet-details', label: 'Planet Details', fields: birthFields() },
    { method: 'POST', path: '/kp/cuspal-lords', label: 'Cuspal Lords', fields: birthFields() },
    { method: 'POST', path: '/kp/bhav-chalit', label: 'Bhav Chalit', fields: birthFields() },
    { method: 'POST', path: '/kp/ruling-planets', label: 'Ruling Planets', fields: birthFields() },
    { method: 'POST', path: '/kp/horary', label: 'Horary (Prashna)', fields: [{ key: 'questionDate', label: 'Question Date', type: 'date', group: 'Question' }, { key: 'questionTime', label: 'Question Time', type: 'time', group: 'Question' }, { key: '_location', label: 'Location', type: 'location', group: 'Question' }, { key: 'question', label: 'Question', type: 'textarea', placeholder: 'Will I get a job this year?', group: 'Question' }] },
    { method: 'POST', path: '/kp/star-lords', label: 'Star Lords', fields: birthFields() },
  ],
}
