import { useRef } from 'react'
import { motion, useInView } from 'framer-motion'
import { FileText } from 'lucide-react'

function FadeIn({ children, delay = 0 }) {
  const ref = useRef(null)
  const isInView = useInView(ref, { once: true, margin: '-60px' })
  return (
    <motion.div ref={ref}
      initial={{ opacity: 0, y: 30 }}
      animate={isInView ? { opacity: 1, y: 0 } : {}}
      transition={{ duration: 0.6, delay, ease: [0.22, 1, 0.36, 1] }}>
      {children}
    </motion.div>
  )
}

const sectionStyle = { marginBottom: 24 }
const headingStyle = { fontSize: 20, fontWeight: 700, marginBottom: 10 }
const textStyle = { color: '#94a3b8', fontSize: 15, lineHeight: 1.8, marginBottom: 12 }

export default function Terms() {
  return (
    <div style={{ paddingTop: 100 }}>
      <section className="section" style={{ maxWidth: 800 }}>
        <FadeIn>
          <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 8, justifyContent: 'center' }}>
            <FileText size={24} color="#7c3aed" />
            <p style={{ color: '#64748b', fontSize: 13, textTransform: 'uppercase', letterSpacing: 2.5, fontWeight: 600 }}>Terms of Service</p>
          </div>
          <h1 style={{ fontSize: 'clamp(28px, 4vw, 44px)', fontWeight: 900, textAlign: 'center', marginBottom: 12, letterSpacing: '-1px' }}>
            Terms of <span className="gradient-text">Service</span>
          </h1>
          <p style={{ color: '#64748b', fontSize: 14, textAlign: 'center', marginBottom: 48 }}>
            Last updated: July 29, 2026
          </p>
        </FadeIn>

        <FadeIn delay={0.1}>
          <div style={{ background: 'var(--bg-card)', border: '1px solid var(--border-color)', borderRadius: 'var(--radius-lg)', padding: 40 }}>
            <div style={sectionStyle}>
              <h2 style={headingStyle}>1. Acceptance of Terms</h2>
              <p style={textStyle}>
                By accessing or using the AstroVakta API ("Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service. We reserve the right to update these terms at any time with reasonable notice.
              </p>
            </div>

            <div style={sectionStyle}>
              <h2 style={headingStyle}>2. API Usage & Rate Limits</h2>
              <p style={textStyle}>
                API access is granted based on your subscription tier. You agree to respect rate limits associated with your tier. Exceeding rate limits may result in temporary throttling or suspension of your API key. You may not circumvent rate limits through multiple accounts or API keys.
              </p>
            </div>

            <div style={sectionStyle}>
              <h2 style={headingStyle}>3. Acceptable Use</h2>
              <p style={textStyle}>
                You agree not to use the Service for any illegal or unauthorized purpose. You may not: (a) resell the API without proper authorization, (b) scrape or download data in bulk for redistribution, (c) use the Service to build competing products, (d) reverse engineer or attempt to extract the source code of the Service.
              </p>
            </div>

            <div style={sectionStyle}>
              <h2 style={headingStyle}>4. AI Provider Usage</h2>
              <p style={textStyle}>
                Our BYO AI key feature allows you to use your own API keys with third-party AI providers. You are solely responsible for the costs incurred through your AI provider accounts and for complying with each provider's terms of service. AstroVakta is not liable for charges, rate limits, or content generated by third-party AI providers.
              </p>
            </div>

            <div style={sectionStyle}>
              <h2 style={headingStyle}>5. Intellectual Property</h2>
              <p style={textStyle}>
                The AstroVakta API, documentation, branding, and all related materials are the intellectual property of AstroVakta. The astrological data returned by the API (birth charts, predictions, etc.) is yours to use freely in your applications. You retain all rights to the data you generate through the API.
              </p>
            </div>

            <div style={sectionStyle}>
              <h2 style={headingStyle}>6. Service Availability</h2>
              <p style={textStyle}>
                We strive for 99.9% uptime but do not guarantee uninterrupted access. We may perform scheduled maintenance with advance notice. In case of outages, we will make reasonable efforts to restore service promptly.
              </p>
            </div>

            <div style={sectionStyle}>
              <h2 style={headingStyle}>7. Limitation of Liability</h2>
              <p style={textStyle}>
                The Service is provided "as is" without warranty of any kind. AstroVakta is not liable for any damages arising from the use of the Service, including but not limited to incorrect astrological data, service interruptions, or third-party AI provider failures.
              </p>
            </div>

            <div style={sectionStyle}>
              <h2 style={headingStyle}>8. Account Termination</h2>
              <p style={textStyle}>
                We reserve the right to suspend or terminate accounts that violate these terms. You may cancel your account at any time. Refunds are handled according to our refund policy, which is available on request.
              </p>
            </div>

            <div style={sectionStyle}>
              <h2 style={headingStyle}>9. Contact</h2>
              <p style={textStyle}>
                For questions about these terms, contact us at hello@astrovakta.com or via WhatsApp at +91 62394 02519.
              </p>
            </div>
          </div>
        </FadeIn>
      </section>
    </div>
  )
}
